local load_opts = function(filename)
	require("ethan.plugin_opts." .. filename)
end

load_opts("telescope")
load_opts("autopairs")
load_opts("autotag")
load_opts("comment")
load_opts("lualine")
load_opts("transparent")
load_opts("toggleterm")
load_opts("alpha")
load_opts("impatient")
load_opts("cmp")
load_opts("nvim-tree")
load_opts("floaterm")
load_opts("gitsigns")
load_opts("which-key")
